services:
  - type: web
    name: comunidad-cobros-api
    env: node
    rootDir: apps/api
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_ORIGIN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: COOKIE_SECURE
        value: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_FULL_NAME
        sync: false
  - type: web
    name: comunidad-cobros-web
    env: static
    rootDir: apps/web
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false
